### ISSUE TITLE
UnboundLocalError in duplicate image segregation

### ISSUE THREAD

**Issue by rbunn80110** [nav9/duplicateFileFinder#1]
Traceback (most recent call last):
  File "/home/bob/PycharmProjects/duplicateFileFinder/main/main.py", line 646, in <module>
    fileSearcher.search()        
  File "/home/bob/PycharmProjects/duplicateFileFinder/main/main.py", line 518, in search
    self.__markAlreadyProcessedFile__(folderOrdinal, fileOrdinal)
UnboundLocalError: local variable 'fileOrdinal' referenced before assignment

**Comment by nav9** [comment]
It was an indentation bug. Fixed it. Thank you very much, rbunn80110, for reporting this :-)
